name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v20

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: holochain-ci

      - name: Cache Cargo and Rust Build
        uses: actions/cache@v2
        if: always()  # build artifacts are correct even if job fails
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install nix packages
        run: nix develop -c $SHELL -c "echo Nix packages installed"

      - name: Install JS packages
        run: nix develop -c $SHELL -c "npm ci"

      - name: Build Happ
        run: nix develop -c $SHELL -c "npm run build:happ"

      - name: Test with sweettest
        run: nix develop -c $SHELL -c "npm run test:sweet"

      - name: Test with tryorama
        run: nix develop -c $SHELL -c "npm test"

      - name: Clippy
        run: nix develop -c $SHELL -c "npm run cargo:clippy"

      - name: Check rust formatting
        run: nix develop -c $SHELL -c "npm run cargo:fmt:check"
