name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "main"

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-test:
    timeout-minutes: 300
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v20

      - name: Set up cachix
        uses: cachix/cachix-action@v12
        with:
          name: holochain # this is our cachix cache; we can write to it as well as read
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        # with:
        #   name: holochain-ci   # this is the official holochain-ci; not always up to date; read-only for us

      - name: Cache Cargo and Rust Build
        uses: actions/cache@v2
        with:
          path: |
            .cargo/bin/
            .cargo/registry/index/
            .cargo/registry/cache/
            .cargo/git/db/
            target
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}

      - name: Install nix packages
        run: nix develop -c $SHELL -c "echo Nix packages installed"

      - name: Install JS packages
        run: nix develop -c $SHELL -c "npm ci"

      - name: Test with tryorama
        run: nix develop -c $SHELL -c "npm test"
